version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "8001:8001"
version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "88:3000"
